from PyQt5 import QtCore, QtGui, QtWidgets
import PatientReg
import ViewPatients
import EmployeeReg
import ViewEmp
import GenerateBill
import ViewBills
import AdminAppointments

class Admin_Form( object ):
    # Function to show Appointment Form
    def Appointments(self):
        self.window = QtWidgets.QMainWindow()
        self.Open = AdminAppointments.AdminShowAppointments()
        self.Open.setupUi( self.window )
        self.window.show()
    # Function to OpenWindow View Bills Form
    def OpenViewBills(self):
        self.window = QtWidgets.QMainWindow()
        self.Open = ViewBills.ViewBillsAdmin()
        self.Open.setupUi( self.window )
        self.window.show()
    # Function to open Generate Bill Form
    def OpenGenerateBill(self):
        self.window = QtWidgets.QMainWindow()
        self.Open = GenerateBill.Generate_Bill()
        self.Open.setupUi( self.window )
        self.window.show()
    # Function to OpenWindow view Employees Form
    def OpenViewEMP(self):
        self.window = QtWidgets.QMainWindow()
        self.Open = ViewEmp.ViewEmployees()
        self.Open.setupUi( self.window )
        self.window.show()
    # Function to open Employee Registration Form
    def OpenEmployeeReg(self):
        self.window = QtWidgets.QMainWindow()
        self.Open = EmployeeReg.EmployeeRegistration()
        self.Open.setupUi( self.window )
        self.window.show()
    # Function to open View Patients Form
    def OpenViewPatients(self):
        self.window = QtWidgets.QMainWindow()
        self.Open = ViewPatients.ViewPatientsAdmin()
        self.Open.setupUi( self.window )
        self.window.show()
    # Function to open Patient Registration Form
    def OpenPatientReg(self):
        self.window = QtWidgets.QMainWindow()
        self.Open = PatientReg.RegistrationPatientsAdmin()
        self.Open.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindowAdmin):
        MainWindowAdmin.setObjectName( "MainWindowAdmin" )
        MainWindowAdmin.resize( 702, 554 )
        self.centralwidget = QtWidgets.QWidget( MainWindowAdmin )
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 211, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Logo.png"))
        self.label_2.setObjectName("label_2")
        self.PatientRegB = QtWidgets.QPushButton(self.centralwidget)
        self.PatientRegB.setGeometry(QtCore.QRect(60, 200, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.PatientRegB.setFont(font)
        self.PatientRegB.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.PatientRegB.setObjectName("PatientRegB")
        self.PatientRegB.clicked.connect(self.OpenPatientReg)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 531))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("H.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 120, 411, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(117, 214, 211);")
        self.label_3.setObjectName("label_3")
        self.AppButton = QtWidgets.QPushButton(self.centralwidget)
        self.AppButton.setGeometry(QtCore.QRect(440, 310, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.AppButton.setFont(font)
        self.AppButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AppButton.setObjectName("AppButton")
        self.AppButton.clicked.connect(self.Appointments)
        self.PatientInfoB = QtWidgets.QPushButton(self.centralwidget)
        self.PatientInfoB.setGeometry(QtCore.QRect(210, 200, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.PatientInfoB.setFont(font)
        self.PatientInfoB.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"\n"
"")
        self.PatientInfoB.setObjectName("PatientInfoB")
        self.PatientInfoB.clicked.connect(self.OpenViewPatients)
        self.BillRecB = QtWidgets.QPushButton(self.centralwidget)
        self.BillRecB.setGeometry(QtCore.QRect(290, 310, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.BillRecB.setFont(font)
        self.BillRecB.setStyleSheet("\n"
"background-color: rgb(85, 170, 255);")
        self.BillRecB.setObjectName("BillRecB")
        self.BillRecB.clicked.connect(self.OpenViewBills)
        self.GenerateB = QtWidgets.QPushButton(self.centralwidget)
        self.GenerateB.setGeometry(QtCore.QRect(140, 310, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.GenerateB.setFont(font)
        self.GenerateB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.GenerateB.setObjectName("GenerateB")

        self.GenerateB.clicked.connect(self.OpenGenerateBill)
        self.StaffInfoB = QtWidgets.QPushButton(self.centralwidget)
        self.StaffInfoB.setGeometry(QtCore.QRect(510, 200, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.StaffInfoB.setFont(font)
        self.StaffInfoB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.StaffInfoB.setObjectName("StaffInformation")
        self.StaffInfoB.clicked.connect(self.OpenViewEMP)
        self.StaffRegistB = QtWidgets.QPushButton(self.centralwidget)
        self.StaffRegistB.setGeometry(QtCore.QRect(360, 200, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.StaffRegistB.setFont(font)
        self.StaffRegistB.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.StaffRegistB.setObjectName("StaffRegistration")
        self.StaffRegistB.clicked.connect(self.OpenEmployeeReg)
        self.LogOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogOutButton.setGeometry(QtCore.QRect(290, 410, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LogOutButton.setFont(font)
        self.LogOutButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LogOutButton.setObjectName("LogOutB")
        self.LogOutButton.clicked.connect(QtWidgets.qApp.quit)
        self.label.raise_()
        self.label_2.raise_()
        self.PatientRegB.raise_()
        self.label_3.raise_()
        self.AppButton.raise_()
        self.PatientInfoB.raise_()
        self.BillRecB.raise_()
        self.GenerateB.raise_()
        self.StaffInfoB.raise_()
        self.StaffRegistB.raise_()
        self.LogOutButton.raise_()
        MainWindowAdmin.setCentralWidget( self.centralwidget )
        self.menubar = QtWidgets.QMenuBar( MainWindowAdmin )
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 21))
        self.menubar.setObjectName("menubar")
        MainWindowAdmin.setMenuBar( self.menubar )
        self.statusbar = QtWidgets.QStatusBar( MainWindowAdmin )
        self.statusbar.setObjectName("statusbar")
        MainWindowAdmin.setStatusBar( self.statusbar )

        self.retranslateUi( MainWindowAdmin )
        QtCore.QMetaObject.connectSlotsByName( MainWindowAdmin )

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindowAdmin", "MainWindowAdmin"))
        self.PatientRegB.setText(_translate("MainWindowAdmin", "Patient Registration"))
        self.label_3.setText(_translate("MainWindowAdmin", "Welcome to the Care & Cure Hospital!"))
        self.AppButton.setText(_translate("MainWindowAdmin", "Appointments"))
        self.PatientInfoB.setText(_translate("MainWindowAdmin", "Patients Information"))
        self.BillRecB.setText(_translate("MainWindowAdmin", "Bill Record"))
        self.GenerateB.setText(_translate("MainWindowAdmin", "Generate Bill"))
        self.StaffInfoB.setText(_translate("MainWindowAdmin", "Staff Information"))
        self.StaffRegistB.setText(_translate("MainWindowAdmin", "Staff Registration"))
        self.LogOutButton.setText(_translate("MainWindowAdmin", "Log Out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Admin_Form()
    ui.setupUi( MainWindow )
    MainWindow.show()
    sys.exit(app.exec_())
